volumeClaimTemplate:
  resources:
    requests:
      storage: 10Gi

secret:
  password: ${password}

# This allows ES to accept https connections without username/password.
esConfig:
  elasticsearch.yml: |
    xpack.security.authc:
        anonymous:
          username: anonymous
          roles: superuser
          authz_exception: false
